language: python
python: "3.6"
services:
  - redis-server
  - mysql
  - postgresql
env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py36
  - TOXENV=lint
matrix:
  include:
  - python: "3.5"
    env: TOXENV=py35
install:
  - pip install tox coveralls
before_script:
  - mysql -e 'create database test;'
script: tox
after_success:
  if [ "$TOXENV" == "py27" ]; then coveralls; fi
